language: java
sudo: false

addons:
  sonarcloud:
    organization: "ceciliacal"
    token: "9dec0af2e72859868064557aad6dfe58c169a577" 

matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk11
    - os: linux
      arch: s390x
      jdk: openjdk11
      addons:
        apt:
          update: true
          packages:
            - maven
            - libcppunit-dev

cache:
  directories:
  - "$HOME/.m2"

addons:
  apt:
    packages:
    - libcppunit-dev
  
  sonarcloud:
    organization: "ceciliacal"
    token: "9dec0af2e72859868064557aad6dfe58c169a577" 
    
 install: 
  - mvn clean install -q -DskipTests=true 

script: 
  - mvn clean apache-rat:check verify -DskipTests spotbugs:check checkstyle:check -Pfull-build
  - mvn clean verify sonar:sonar  -Dsonar.projectKey=ceciliacal_bookkeeper 

branches:
  only:
  - master
  - branch-3.5
  - branch-3.4
