language: java
sudo: false
jdk:
  #- openjdk8
  - openjdk11

cache:
  directories:
  - "$HOME/.m2"

addons:
  apt:
    packages:
    - libcppunit-dev
    
  sonarcloud:
    organization: "ceciliacal"
    token: "da523a61ed1f68aec3d793163534cdd222350f13"  
    

install: mvn clean install -q -DskipTests=true

script: mvn clean verify  sonar:sonar spotbugs:check checkstyle:check -Pfull-build

branches:
  only:
  - master
  - branch-3.5
  - branch-3.4