language: java
sudo: false
jdk:
  - openjdk8
  #- openjdk11

cache:
  directories:
  - "$HOME/.m2"

addons:
  apt:
    packages:
    - libcppunit-dev
    
 addons:
  sonarcloud:
    organization: ceciliacal
    token: 331a1df367982550e16360321497cab14c6a817e   

script: mvn clean install -q -Ppit sonar:sonar -Dsonar.projectKey=ceciliacal_zookeeper -DskipTests spotbugs:check checkstyle:check -Pfull-build

branches:
  only:
  - master
  - branch-3.5
  - branch-3.4