language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: ceciliacal
    token: fad53637bf43a0c773384d695521687f191475bd

install: 
  - mvn clean install -q -DskipTests=true 

script:
  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ceciliacal_zookeeper 
