language: java
sudo: false
jdk:
  - openjdk8
 # - openjdk11

cache:
  directories:
  - "$HOME/.m2"

addons:
  apt:
    packages:
    - libcppunit-dev
    
  sonarcloud:
    organization: ceciliacal
    token: 331a1df367982550e16360321497cab14c6a817e

script: mvn clean install sonar:sonar  -Dsonar.projectKey=ceciliacal_bookkeeper  spotbugs:check checkstyle:check -Pfull-build

branches:
  only:
  - master
  - branch-3.5
  - branch-3.4
